#pragma once

#define VERSION "0.1.0"
#define AUTHOR "Kerneels Bezuidenhout"
#define BUAD_RATE 115200

#define RF_INPUT_PIN 17
#define RF_INPUT_DEBOUNCE 50

#define MOTORS_DIRECTION_SWITCH_PIN 15
#define MOTORS_DIRECTION_SWITCH_DEBOUNCE 50
#define MOTOR_RELAY_A_PIN 12
#define MOTOR_RELAY_B_PIN 13
